name:                liva
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- split
- time
- directory

library:
  source-dirs: src

executables:
  liva-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liva
    - optparse-applicative

tests:
  liva-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liva
    - tasty
    - tasty-hunit
